### PR TITLE
fix(): Remove @input in favor of @update:modelValue

### LINKED ISSUE #1657: Remove @input in favor of @update:modelValue
### Describe the bug

Read title. Not sure if I want to do this yet

### Reproduction

n

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by anrolmar**
# Describe the PR

Change @input for @update:modelValue event in BFormCheckbox, BFormCheckboxGroup, BFormRadio, BFormRadioGroup, BFormSelect, BFormTags and useFormInput

fix #1657

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

File: packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue [hunk 1]
```diff
@@ -19,7 +19,7 @@
       :false-value="uncheckedValue"
       :indeterminate="indeterminateBoolean"
       @change="modelValue !== undefined && emit('change', modelValue)"
-      @input="modelValue !== undefined && emit('input', modelValue)"
+      @input="modelValue !== undefined && emit('update:modelValue', modelValue)"
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue:22]: So there is some additional complexity to this issue that isn't spoken about in the issue.

The goal is to not treat change or inputs with any specialty. The input event should just be the native input event. In Vue 2, this wasn't possible because the native input event became the modelValue. In Vue 3, we have a custom modelValue/update:modelValue event

So, what we _actually_ want is to just emit the natural value. 

**However**, if the input is not the root component, it doesn't trigger the event upwards. Since this is not the root component, we wouldn't emit it if we just excluded line 21 & 22. 

What we actually want to do instead is simply 

```html
     @change="emit('change', $event)"
     @input="emit('input', $event)"
```
This is what we want to do when the input is not the root component, when it is the root component, we simply exclude the lines and don't treat them with any particular importance. 

This is applied to all input bearing components

File: .release-please-manifest.json [hunk 2]
```diff
@@ -1,4 +1,4 @@
 {
-  "packages/bootstrap-vue-next": "0.15.5",
-  "packages/nuxt": "0.15.5"
+  "packages/bootstrap-vue-next": "0.16.0",
```
Comment (VividLemon) [inline .release-please-manifest.json:2]: Revert this file

File: packages/bootstrap-vue-next/CHANGELOG.md [hunk 3]
```diff
@@ -1,166 +1,186 @@
 # Changelog
 
-## [0.15.5](https://github.com/bootstrap-vue-next/bootstrap-vue-next/compare/bootstrapvuenext-v0.15.4...bootstrapvuenext-v0.15.5) (2023-11-23)
+## [0.16.0](https://github.com/bootstrap-vue-next/bootstrap-vue-next/compare/bootstrapvuenext-v0.15.5...bootstrapvuenext-v0.16.0) (2023-12-24)
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/CHANGELOG.md:3]: (and so on)

File: package.json [hunk 4]
```diff
@@ -37,12 +37,12 @@
   },
   "devDependencies": {
     "husky": "^8.0.3",
-    "lint-staged": "^15.2.0",
+    "lint-staged": "^15.0.2",
```
Comment (VividLemon) [inline package.json:40]: (and so on)

File: apps/playground/tsconfig.app.json [hunk 5]
```diff
@@ -1,5 +1,5 @@
 {
-  "extends": "@vue/tsconfig/tsconfig.dom.json",
+  "extends": ["@vue/tsconfig/tsconfig.dom.json", "@vue/tsconfig/tsconfig.lib.json"],
```
Comment (VividLemon) [inline apps/playground/tsconfig.app.json:2]: Revert this.

You can ignore any of the issues. I will fix them later

File: apps/playground/tsconfig.node.json [hunk 6]
```diff
@@ -1,5 +1,10 @@
 {
-  "extends": ["@tsconfig/node20/tsconfig.json", "@vue/tsconfig/tsconfig.json"],
+  "extends": [
+    "@tsconfig/node20/tsconfig.json",
```
Comment (VividLemon) [inline apps/playground/tsconfig.node.json:3]: (and so on)

File: packages/bootstrap-vue-next/package.json [hunk 7]
```diff
@@ -2,7 +2,7 @@
   "name": "bootstrap-vue-next",
   "displayName": "BootstrapVueNext",
   "description": "BootstrapVueNext is an early and lovely component library for Vue 3 & Nuxt 3 based on Bootstrap 5 and Typescript.",
-  "version": "0.15.5",
+  "version": "0.16.0",
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/package.json:5]: (and so on)

File: packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue [hunk 8]
```diff
@@ -87,9 +87,8 @@ const props = withDefaults(
 )
 
 const emit = defineEmits<{
-  'change': [value: CheckboxValue | CheckboxValue[]]
-  'input': [value: CheckboxValue | CheckboxValue[]]
-  'update:modelValue': [value: CheckboxValue | CheckboxValue[]]
+  change: [event: Event]
+  input: [event: Event]
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue:91]:
```suggestion
  input: [event: Event]
  'update:modelValue': [value: CheckboxValue | CheckboxValue[]]
```
The model value update is still required

File: packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue [hunk 9]
```diff
@@ -78,9 +78,8 @@ const props = withDefaults(
 )
 
 const emit = defineEmits<{
-  'change': [value: RadioValue]
-  'input': [value: RadioValue]
-  'update:modelValue': [value: RadioValue]
+  change: [value: Event]
+  input: [value: Event]
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue:82]:
```suggestion
  input: [value: Event]
  'update:modelValue': [value: RadioValue]
```

File: packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadioGroup.vue [hunk 10]
```diff
@@ -121,7 +120,7 @@ provide(radioGroupKey, {
 })
 
 watch(modelValue, (newValue) => {
-  emit('input', newValue)
+  emit('update:modelValue', newValue)
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadioGroup.vue:123]: In this you're updating the model value to its same value, when the model value changes. It's circular and will likely cause an infinite loop.

Regardless, in the case of "Group" components, the input/change events are custom implementations, and can stay. So, this file, and the BFormSelectOptionGroup can stay the way they are

File: packages/bootstrap-vue-next/src/components/BFormSelect/BFormSelectOptionGroup.vue [hunk 11]
```diff
@@ -35,6 +35,7 @@ const props = withDefaults(
     disabledField: 'disabled',
     htmlField: 'html',
     label: undefined,
+    // eslint-disable-next-line vue/require-valid-default-prop
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BFormSelect/BFormSelectOptionGroup.vue:38]: You can revert this file, I will take a look at this issue later. I'd like to figure out why it's failing -- although it's likely just a vue-eslint problem

File: packages/bootstrap-vue-next/src/components/BFormSpinbutton/BFormSpinbutton.vue [hunk 12]
```diff
@@ -10,7 +10,7 @@
     @click="focused = true"
   >
     <!-- eslint-disable-next-line prettier/prettier -->
-    <slot :name="(buttons.top.slot.name as 'increment' | 'decrement')" :has-focus="focused">
+    <slot :name="`${slotName as 'increment' | 'decrement'}`" :has-focus="focused">
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BFormSpinbutton/BFormSpinbutton.vue:13]: The changes here are wrong. One of these slots is for the top and the other is for the bottom. They are not the same. So, this file can be reverted. I'm not sure why it was changed.

File: packages/bootstrap-vue-next/src/composables/useBooleanish.ts [hunk 13]
```diff
@@ -1,14 +1,23 @@
-import type {Booleanish} from '../types'
+/* eslint-disable no-console */
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/composables/useBooleanish.ts:1]: Revert this file change. The previous code is how it is supposed to be

File: packages/bootstrap-vue-next/tests/composables/useBooleanish.spec.ts [hunk 14]
```diff
@@ -1,6 +1,7 @@
-import {useBooleanish} from '../../src/composables'
+/* eslint-disable no-console */
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/tests/composables/useBooleanish.spec.ts:1]:
```suggestion
```

File: packages/nuxt/CHANGELOG.md [hunk 15]
```diff
@@ -1,127 +1,127 @@
 # Changelog
 
-## [0.15.5](https://github.com/bootstrap-vue-next/bootstrap-vue-next/compare/nuxt-v0.15.4...nuxt-v0.15.5) (2023-11-23)
-
+## [0.16.0](https://github.com/bootstrap-vue-next/bootstrap-vue-next/compare/nuxt-v0.15.5...nuxt-v0.16.0) (2023-12-24)
```
Comment (VividLemon) [inline packages/nuxt/CHANGELOG.md:3]: This file can be reverted. Not sure how this was applied, but 0.16 is not released yet

File: packages/nuxt/package.json [hunk 16]
```diff
@@ -1,7 +1,7 @@
 {
   "name": "@bootstrap-vue-next/nuxt",
   "description": "Nuxt Module for BootstrapVueNext",
-  "version": "0.15.5",
+  "version": "0.16.0",
```
Comment (VividLemon) [inline packages/nuxt/package.json:4]: Revert

File: pnpm-lock.yaml [hunk 17]
```diff
@@ -12,7 +12,7 @@ importers:
         specifier: ^8.0.3
         version: 8.0.3
       lint-staged:
-        specifier: ^15.2.0
+        specifier: ^15.0.2
```
Comment (VividLemon) [inline pnpm-lock.yaml:15]: Revert

**Review by VividLemon — CHANGES_REQUESTED** [review]

File: .release-please-manifest.json (hunk 2 above)
Comment (anrolmar) [reply .release-please-manifest.json:2]: Done

File: packages/bootstrap-vue-next/src/components/BFormSpinbutton/BFormSpinbutton.vue (hunk 12 above)
Comment (anrolmar) [reply packages/bootstrap-vue-next/src/components/BFormSpinbutton/BFormSpinbutton.vue:13]: Because I had some compiling errors (#1698)

**Comment by anrolmar** [comment]
The PR failed because the same errors as https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1681#issuecomment-1868609339

**Comment by VividLemon** [comment]
You should be able to pull in the main branch now and clear out anything that doesn't need to be changed.

File: packages/bootstrap-vue-next/src/components/BFormSpinbutton/BFormSpinbutton.vue [hunk 18]
```diff
@@ -53,7 +53,7 @@
       </bdi>
     </output>
     <!-- eslint-disable-next-line prettier/prettier -->
-    <slot :name="(buttons.bottom.slot.name as 'increment' | 'decrement')" :has-focus="focused">
+    <slot :name="(buttons.top.slot.name as 'increment' | 'decrement')" :has-focus="focused">
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BFormSpinbutton/BFormSpinbutton.vue:56]: Revert the changes in this file

File: packages/bootstrap-vue-next/CHANGELOG.md [hunk 19]
```diff
@@ -1,166 +1,186 @@
 # Changelog
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/CHANGELOG.md:1]: Revert the changes in this file

**Review by VividLemon — CHANGES_REQUESTED** [review]
You are missing changes to BFormInput (the defineEmits needs to be changed, the actual emitting is done in useFormInput)

**Comment by xvaara** [comment]
@VividLemon Are these emits/v-on:xx even needed? Couldn't we just bind attrs to the form element? Or then typescript wouldn't maybe have completion for the events?

**Comment by VividLemon** [comment]
> @VividLemon Are these emits/v-on:xx even needed? Couldn't we just bind attrs to the form element? Or then typescript wouldn't maybe have completion for the events?

The component is a fragment so it won't bubble up without declaring it. Feel free to try it out without explicitly declaring it, AFAIK it shouldn't work

**Comment by VividLemon** [comment]
I'll be looking at this soon. Its been sitting too long lol 🙏

**Comment by anrolmar** [comment]
Because, it seems to have a lot of comments, could you tell me what it needs to be done?

File: packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue [hunk 20]
```diff
@@ -73,7 +73,8 @@ const props = withDefaults(
 )
 
 const emit = defineEmits<{
-  'blur': [val: FocusEvent]
+  // eslint-disable-next-line @typescript-eslint/no-explicit-any
+  'blur': [val: any]
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue:77]: This is still likely a FocusEvent

File: packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue [hunk 21]
```diff
@@ -73,7 +73,8 @@ const props = withDefaults(
...
   // eslint-disable-next-line @typescript-eslint/no-explicit-any
   'change': [val: any]
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue:79]: This input & change are going to be `Event`

Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue:79]: This probably applies to BFormTextarea as well

File: packages/bootstrap-vue-next/src/components/BFormSelect/BFormSelectOptionGroup.vue [hunk 22]
```diff
@@ -19,10 +19,10 @@
 </template>
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BFormSelect/BFormSelectOptionGroup.vue:19]: File `BFormSelect` needs to change its implementation of change/input. 
image
Can be changed to remove input/change
and then it needs to  be added to the select element

```html
<select @input="emit('input', $event)" @change="emit('change', $event) />
```

**Review by VividLemon — CHANGES_REQUESTED** [review]
Then finally, the implementation of useFormInput needs to change its emitted events to be the Event in the onChange/onInput methods of that composable

**Comment by anrolmar** [comment]
The PR is failing because some unit testing related to the BFormCheckbox. Maybe because this PR, https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1725

**Comment by VividLemon** [comment]
> The PR is failing because some unit testing related to the BFormCheckbox. Maybe because this PR, #1725

You accidentally messed up a merge conflict. You have 40 files changed
