### PR TITLE
Better focus for trapped components.

### LINKED ISSUE #2540: BModal does focus twice, with focusTrap and with useFocus.
### Describe the bug

When upgrading the package version from 0.9.23 to 0.26.19,
I noticed a degraded user experience when opening modals due to the modal's default options.
This issue is particularly prominent with input elements in the modal.

It appears to be a conflict between the focus trap and the default autofocus behavior.

### Reproduction

https://stackblitz.com/edit/bootstra-vue-next-template-surj5wgc?file=src%2FApp.vue

### Used Package Manager

npm

### PR DESCRIPTION
**Pull request by xvaara**
feat(BModal)!: remove autofocus and autofocusButton props and add mor…e versitile focus prop
feat(BOffcanvas)!: remove nofocus prop and add more versitile focus prop
feat(BModal): return focus to previous element on close
feat(BOffcanvas): return focus to previous element on close
fix(BModal): set focus only once

closes #2540

# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [x] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

File: packages/bootstrap-vue-next/src/types/ComponentProps.ts [hunk 1]
```diff
@@ -561,6 +561,13 @@ export interface BOffcanvasProps extends TeleporterProps, ShowHideProps {
   bodyAttrs?: Readonly<AttrsValue>
   bodyClass?: ClassValue
   bodyScrolling?: boolean
+  focus?:
+    | 'close'
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/types/ComponentProps.ts:565]: I think a string literal in this case `'close'` will be overshadowed by the more generic `string` type. Making this useless

File: packages/bootstrap-vue-next/src/types/ComponentProps.ts [hunk 2]
```diff
@@ -1281,8 +1287,15 @@ export interface BCardHeadFootProps extends ColorExtendables {
 }
 
 export interface BModalProps extends TeleporterProps, ShowHideProps {
-  autofocus?: boolean
-  autofocusButton?: 'ok' | 'cancel' | 'close'
+  focus?:
+    | 'ok'
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/types/ComponentProps.ts:1291]: Same here

**Review by VividLemon — CHANGES_REQUESTED** [review]

File: packages/bootstrap-vue-next/src/types/ComponentProps.ts (hunk 1 above)
Comment (xvaara) [reply packages/bootstrap-vue-next/src/types/ComponentProps.ts:565]: For some reason my message here didn't save. It's there for the autocomplete
