### PR TITLE
fix(BModal): multiple modals backdrop fix

### LINKED ISSUE #2261: Multiple BModals, overlays not correct in 0.25.0
### Describe the bug

After the 0.25 update, the background overlay isn't showing above lower-level modals.
image

This can be seen in the docs site if you open multiple modals. The top modal is not putting overlay over the "lower" modal.
https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/modal.html#multiple-modal-support

### Reproduction

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/modal.html#multiple-modal-support

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by xvaara**
# Describe the PR

fixes #2261

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

File: packages/bootstrap-vue-next/src/components/BModal/BModal.vue [hunk 1]
```diff
@@ -483,16 +484,23 @@ watch(stackWithoutSelf, (newValue, oldValue) => {
...
+    ? // Just for reference there is a single frame in which the modal is not active but still has a higher z-index than the active ones due to _when_ it calculates its position. It's a small visual effect
+      defaultModalDialogZIndex -
+      ((activeModalCount?.value ?? 0) * 2 - (activePosition?.value ?? 0) * 2)
+    : defaultModalDialogZIndex
+)
+const computedZIndex = computed<CSSProperties>(() => ({
+  'z-index': computedZIndexNumber.value,
+}))
+const computedZIndexBackdrop = computed<CSSProperties>(() => ({
+  'z-index': computedZIndexNumber.value - 1,
```
Comment (xvaara) [inline packages/bootstrap-vue-next/src/components/BModal/BModal.vue:503]: @VividLemon I couldn't think of a easier fix for this. Thoughts?

Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BModal/BModal.vue:503]: Seems fine.

**Review by VividLemon — APPROVED** [review]
