### PR TITLE
fix: Invalid button code in dropdown component

### LINKED ISSUE #1304: Invalid HTML button code used in dropdown component
For example, the sample code from the site:
```vue
<template>
  <BDropdown v-model="show1" text="Button text via Prop" class="m-1">
    <BDropdownItem href="#">An item</BDropdownItem>
    <BDropdownItem href="#">Another item</BDropdownItem>
  </BDropdown>
</template>
```

The HTML code of the generated button for toggling the dropdown will be
```html
<button class="btn btn-md btn-secondary dropdown-toggle" type="button" id="__BVID__292357___BV_dropdown__" aria-expanded="false" aria-haspopup="menu">
  <div class="btn-content">Button text via Prop</div>
</button>
```

Where `<div>` is not allowed to be the child of a `<button>`, which we can know this from w3c validator as well.
image

Changing to `<span>` should solve the problem.

### PR DESCRIPTION
**Pull request by JohKei**
resolves #1304

# Describe the PR

This PR fixes the Issue described in #1304 

This is my very first Pull request in OpenSource. Hope I did everything the way I should!

## Small replication

```
<template>
  <BDropdown v-model='show1' text='Button text via Prop' class='m-1'>
    <BDropdownItem href='#'>An item</BDropdownItem>
    <BDropdownItem href='#'>Another item</BDropdownItem>
  </BDropdown>
</template>

```
Now renders a valid button Code:
```
<button class="btn btn-md btn-secondary dropdown-toggle" type="button" id="__BVID__234593___BV_dropdown__" aria-expanded="false" aria-haspopup="menu">
    <!--v-if-->
    <span class="btn-content">Button text via Prop</span>
</button>
```
## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [X ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [ X] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

**Comment by VividLemon** [comment]
I was planning on doing some research later to see what the actual purpose of the element is. From my understanding, the div may be able yo be remove completely. I think it is the remnants of some bootstrao-vue code, but I'm not sure why it exists

**Comment by JohKei** [comment]
It's there to make the textContent of the Button transparent in case we give 
```loading && loading-mode='fill'``` Props to the BButton-component.

```<BButton loading loading-mode="fill"> Hello </BButton>```

Screenshot from 2023-07-20 16-51-54
This replaces the TextContent of the Button with a spinning Spinner by applying the class ```btn-loading-fill``` to the span
```
 .btn-content {
    display: inline-block;

    &.btn-loading-fill {
      color: transparent;
    }
  }
  ``` 
and rendering the spinner-wrapper with ```v-if="loadingBoolean"```

```
  <component
    :is="computedTag"
    class="btn"
    :class="computedClasses"
    v-bind="computedAttrs"
    @click="clicked"
  >
    <div
      v-if="loadingBoolean"
      class="btn-loading"
      :class="{'mode-fill': loadingMode === 'fill', 'mode-inline': loadingMode === 'inline'}"
    >
      <slot name="loading">
        <BSpinner class="btn-spinner" :small="size !== 'lg'" />
      </slot>
    </div>
    <span
      class="btn-content"
      :class="{'btn-loading-fill': loadingBoolean && loadingMode === 'fill'}"
    >
      <slot />
    </span>
  </component>
  ```




If the ```span``` is missing and those props are given, both the spinner and text will be seen at the same time
Screenshot from 2023-07-20 16-47-11

**Comment by VividLemon** [comment]
There's likely a more efficient method that involves removing the classes and replacing them with dynic vif statements

**Comment by JohKei** [comment]
I will try to come up with a better and more efficient solution tomorrow. 

> There's likely a more efficient method that involves removing the classes and replacing them with dynamic vif statements

**Comment by VividLemon** [comment]
> I will try to come up with a better and more efficient solution tomorrow.
> 
> > There's likely a more efficient method that involves removing the classes and replacing them with dynamic vif statements

Take it as far as you can tyvm

**Comment by VividLemon** [comment]
The expected structure is going to be more like this https://getbootstrap.com/docs/5.3/components/spinners/#buttons just with some Vue dynamic code

**Comment by JohKei** [comment]
> The expected structure is going to be more like this https://getbootstrap.com/docs/5.3/components/spinners/#buttons just with some Vue dynamic code

Simplified BButton.vue as far as i could. 
I hope i meet your expectations!

**Comment by JohKei** [comment]
It might also be an option to completely remove the ability to add this spinner to the <BButton> through Props. However, we would still retain the ability to add it using the method described in the BSpinners-Docs.
Screenshot from 2023-07-21 12-06-18

File: packages/bootstrap-vue-next/src/components/BButton/BButton.vue [hunk 1]
```diff
@@ -52,7 +41,7 @@ const props = withDefaults(
       type?: ButtonType
       variant?: ButtonVariant | null
       loading?: Booleanish
-      loadingMode?: 'fill' | 'inline'
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BButton/BButton.vue:55]: Change this back please. Everything else looks good though

**Review by VividLemon — CHANGES_REQUESTED** [review]

File: packages/bootstrap-vue-next/src/components/BButton/BButton.vue [hunk 2]
```diff
@@ -6,21 +6,10 @@
...
-    >
-      <slot name="loading">
-        <BSpinner class="btn-spinner" :small="size !== 'lg'" />
-      </slot>
-    </div>
-    <div
-      class="btn-content"
-      :class="{'btn-loading-fill': loadingBoolean && loadingMode === 'fill'}"
-    >
+    <BSpinner v-if="loadingBoolean" class="btn-spinner" :small="size !== 'lg'" />
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BButton/BButton.vue:9]:
```suggestion
   <slot name="loading" v-if="loadingBoolean">
    <BSpinner class="btn-spinner" :small="size !== 'lg'" />
    </slot>
```
Double check my work please

Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BButton/BButton.vue]: Some of the remaining classes may be unnecessary. Perhaps you could look into that as well

Comment (JohKei) [reply packages/bootstrap-vue-next/src/components/BButton/BButton.vue]: works fine!

Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BButton/BButton.vue]: https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1309#discussion_r1270675270

Btn content and btn spinner might not be useful. Assuming they look similar enough, they van be removed

File: packages/bootstrap-vue-next/src/components/BButton/BButton.vue [hunk 3]
```diff
@@ -6,21 +6,12 @@
...
-      </slot>
-    </div>
-    <div
-      class="btn-content"
-      :class="{'btn-loading-fill': loadingBoolean && loadingMode === 'fill'}"
-    >
+    <slot v-if="loadingBoolean" name="loading">
+      <BSpinner class="btn-spinner" :small="size !== 'lg'" />
+    </slot>
+    <span v-if="(loadingBoolean && !fillBoolean) || !loadingBoolean" class="btn-content">
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BButton/BButton.vue:12]: If the classes can be removed the span here could just use a template fragment.
```suggestion
    <template v-if="(loadingBoolean && !fillBoolean) || !loadingBoolean">
```
Though, I don't think it makes much of a difference.

Comment (JohKei) [reply packages/bootstrap-vue-next/src/components/BButton/BButton.vue:12]: > If the classes can be removed the span here could just use a template fragment.
> 
> Though, I don't think it makes much of a difference.

We can work with removing .btn-content.
But I'm not quite sure with removing .btn-spinner

Comment (JohKei) [reply packages/bootstrap-vue-next/src/components/BButton/BButton.vue:12]: nvm my bad, changes coming

**Comment by VividLemon** [comment]
Okay, now the only remaining issue is the changes to the tests. If you'd like, I can work on this later. Sometime next week. Regardless, I also would like to directly compare the appearance of both the current bbutton and your changes. Just to see if anything is noticeable. If you'd like, you can upload a video comparing the two documentation pages, one locally and one that's online. However, I can also do this later if its too difficult.  

If both of these things are a challenge, I can finish this up and get it released sometime next week.

**Comment by JohKei** [comment]
> 

I haven't yet made any experience doing any of this. I don't mind if you take over. Thanks!

**Comment by JohKei** [comment]
Thats the video with the latest Version of the current Bootstrap-vue-next playing around with BButton & BDropdown:
[Screencast from 23.07.2023 12:18:57.webm](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/117248962/9a65a98f-de2c-42db-bc15-e57ee6dfeada)

And here is the video of the current PR playing around with BButton & BDropdown:
[Screencast from 23.07.2023 12:27:46.webm](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/117248962/1caf0346-eeba-4b5c-8591-7f40ac1e677e)



> Okay, now the only remaining issue is the changes to the tests. If you'd like, I can work on this later. Sometime next week. Regardless, I also would like to directly compare the appearance of both the current bbutton and your changes. Just to see if anything is noticeable. If you'd like, you can upload a video comparing the two documentation pages, one locally and one that's online. However, I can also do this later if its too difficult.
> 
> If both of these things are a challenge, I can finish this up and get it released sometime next week.

File: packages/bootstrap-vue-next/src/components/BButton/BButton.vue [hunk 4]
```diff
@@ -6,21 +6,12 @@
...
-      </slot>
-    </div>
-    <div
-      class="btn-content"
-      :class="{'btn-loading-fill': loadingBoolean && loadingMode === 'fill'}"
-    >
+    <slot v-if="loadingBoolean" name="loading">
+      <BSpinner :small="size !== 'lg'" />
+    </slot>
+    <template v-if="(loadingBoolean && !fillBoolean) || !loadingBoolean">
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BButton/BButton.vue:12]: Instead of this vif, instead dynamically apply the visually-hidden class. It might need to be wrapped in a span again lol. I forgot this vif will remove some a11y context that would be useful

Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BButton/BButton.vue:12]: Or would it be better to add an aria label to the spinner 🤔 otherwise the visually hidden content would just say whatever the content was, and not convey that its loading

Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BButton/BButton.vue:12]: Definitely use this https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/0ba497a0792fab5d6852c77be4bd8443ae1e546c/packages/bootstrap-vue-next/src/components/BSpinner.vue#L22 on the spinner. It will need to be a prop and or slot on the bbutton. Preferably both

File: packages/bootstrap-vue-next/src/components/BButton/BButton.vue [hunk 5]
```diff
@@ -6,21 +6,12 @@
...
-      <slot name="loading">
-        <BSpinner class="btn-spinner" :small="size !== 'lg'" />
-      </slot>
-    </div>
-    <div
-      class="btn-content"
-      :class="{'btn-loading-fill': loadingBoolean && loadingMode === 'fill'}"
-    >
+    <slot v-if="loadingBoolean" name="loading">
+      <BSpinner :small="size !== 'lg'" />
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BButton/BButton.vue:10]:
```suggestion
      <BSpinner :small="size !== 'lg'">
        <slot name="loadingLabel">
          {{ loadingLabel }}
        </slot>
      </BSpinner>
```
Lint & add the prop for the above comment

Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BButton/BButton.vue:10]: This actually brings a unique issue as if the loading mode is inline, then you'd have two items of text.

So the best I would think is to have the label be on the spinner, then add another span text with a vif that changes the text as well

Comment (JohKei) [reply packages/bootstrap-vue-next/src/components/BButton/BButton.vue:10]: Unfortunately, I don't quite understand it yet. I'll take a look at it again tomorrow.

Comment (JohKei) [reply packages/bootstrap-vue-next/src/components/BButton/BButton.vue:10]: > This actually brings a unique issue as if the loading mode is inline, then you'd have two items of text read by a screen reader
> 
> So the best I would think is to have the label be on the spinner, then add another span text with a vif that changes the text as well
> 
> So the spinner will not announce the spinner text when inline, but instead announce the loading text span. If that makes sense

To clarify the suggested change:

This component should have three states for the Button:

1. Button is not in a loading state:
   "Button, Click me"

2. Button is in a loading state, displayed inline:
   "Button, loading, Click me"

3. Button is in a loading state, displayed as a filled loading indicator:
   "Button, loading"

Or am I wrong?

Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BButton/BButton.vue:10]:
```html
    <template v-if="loadingBoolean">
      <template v-if="!loadingFillBoolean">
        {{ loadingText }}
      </template>
      <slot name="loading">
        <BSpinner :small="size !== 'lg'" :label="loadingFillBoolean ? loadingText : undefined" />
      </slot>
    </template>
    <template v-else>
      <slot />
    </template>
```

This is my complete product,

```html
<template>
  <component
    :is="computedTag"
    class="btn"
    :class="computedClasses"
    :aria-disabled="nonStandardTag ? disabledBoolean : null"
    :aria-pressed="isToggle ? pressedBoolean : null"
    :autocomplete="isToggle ? 'off' : null"
    :disabled="isButton ? disabledBoolean : null"
    :href="props.href"
    :rel="computedLink ? props.rel : null"
    :role="nonStandardTag || computedLink ? 'button' : null"
    :target="computedLink ? props.target : null"
    :type="isButton ? props.type : null"
    :to="!isButton ? props.to : null"
    :append="computedLink ? props.append : null"
    :active-class="isBLink ? activeClass : null"
    :event="isBLink ? event : null"
    :replace="isBLink ? replace : null"
    :router-component-name="isBLink ? routerComponentName : null"
    :router-tag="isBLink ? routerTag : null"
    @click="clicked"
  >
    <template v-if="loadingBoolean">
      <template v-if="!loadingFillBoolean">
        {{ loadingText }}
      </template>
      <slot name="loading">
        <BSpinner :small="size !== 'lg'" :label="loadingFillBoolean ? loadingText : undefined" />
      </slot>
    </template>
    <template v-else>
      <slot />
    </template>
  </component>
</template>

<script setup lang="ts">
import {computed} from 'vue'
import BSpinner from '../BSpinner.vue'
import {useBooleanish} from '../../composables'
import type {BLinkProps, Booleanish, ButtonType, ButtonVariant, Size} from '../../types'
import {isLink} from '../../utils'
import BLink from '../BLink/BLink.vue'
import {useVModel} from '@vueuse/core'

defineSlots<{
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  default?: (props: Record<string, never>) => any
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  loading?: (props: Record<string, never>) => any
}>()

const props = withDefaults(
  defineProps<
    {
      pill?: Booleanish
      pressed?: Booleanish
      size?: Size
      squared?: Booleanish
      tag?: string
      type?: ButtonType
      variant?: ButtonVariant | null
      loading?: Booleanish
      loadingFill?: Booleanish
      block?: Booleanish
      loadingText?: string
    } & Omit<BLinkProps, 'variant'>
  >(),
  {
    active: false,
    pill: false,
    pressed: undefined,
    size: 'md',
    squared: false,
    tag: 'button',
    type: 'button',
    variant: 'secondary',
    loading: false,
    loadingFill: false,
    block: false,
    loadingText: 'Loading...',
    // Link props
    activeClass: 'router-link-active',
    append: false,
    disabled: false,
    event: 'click',
    href: undefined,
    // noPrefetch: {type: [Boolean, String] as PropType<Booleanish>, default: false},
    // prefetch: {type: [Boolean, String] as PropType<Booleanish>, default: null},
    rel: undefined,
    replace: false,
    routerComponentName: 'router-link',
    routerTag: 'a',
    target: '_self',
    to: undefined,
    opacity: undefined,
    opacityHover: undefined,
    underlineVariant: null,
    underlineOffset: undefined,
    underlineOffsetHover: undefined,
    underlineOpacity: undefined,
    underlineOpacityHover: undefined,
    icon: false,
    // End link props
  }
)

const emit = defineEmits<{
  'click': [value: MouseEvent]
  'update:pressed': [value: boolean]
}>()

const pressedValue = useVModel(props, 'pressed', emit)

const activeBoolean = useBooleanish(() => props.active)
const blockBoolean = useBooleanish(() => props.block)
const disabledBoolean = useBooleanish(() => props.disabled)
const pillBoolean = useBooleanish(() => props.pill)
const pressedBoolean = useBooleanish(() => props.pressed)
const squaredBoolean = useBooleanish(() => props.squared)
const loadingBoolean = useBooleanish(() => props.loading)
const loadingFillBoolean = useBooleanish(() => props.loadingFill)

const isToggle = computed<boolean>(() => typeof pressedBoolean.value === 'boolean')
const isButton = computed<boolean>(
  () => props.tag === 'button' && props.href === undefined && props.to === undefined
)
const computedLink = computed<boolean>(() => isLink(props))
const isBLink = computed<boolean>(() => props.to !== undefined)
const nonStandardTag = computed<boolean>(() => (props.href !== undefined ? false : !isButton.value))

const computedClasses = computed(() => [
  [`btn-${props.size}`],
  {
    [`btn-${props.variant}`]: props.variant !== null,
    'btn-block': blockBoolean.value,
    'active': activeBoolean.value || pressedBoolean.value,
    'rounded-pill': pillBoolean.value,
    'rounded-0': squaredBoolean.value,
    'disabled': disabledBoolean.value,
  },
])

const computedTag = computed<string | typeof BLink>(() =>
  isBLink.value ? BLink : props.href ? 'a' : props.tag
)

const clicked = (e: MouseEvent): void => {
  if (disabledBoolean.value) {
    e.preventDefault()
    e.stopPropagation()
    return
  }
  emit('click', e)
  if (isToggle.value) {
    pressedValue.value = !pressedBoolean.value
  }
}
</script>
```

(Mind that I made some merge conflicts)

Feel free to copy/paste this code into your PR so we can push this forward.

Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BButton/BButton.vue:10]: It contains an issue where when you go to loading, it will alter the size of the button, but this is a different issue that can be fixed later... If it can be considered a "bug"

Comment (JohKei) [reply packages/bootstrap-vue-next/src/components/BButton/BButton.vue]: Just pushed your Changes. Sorry that I could not follow
