### PR TITLE
 fix(useFocusTrap): dont deactivate focus on esc fixes #2144 

### LINKED ISSUE #2144: BModal deactivates focus trap on esc key
### Describe the bug

When using `BModal` with `noCloseOnEsc` set to `true` or when one of the modal's child elements wants to handle esc key and prevent dialog closure manually, pressing esc key inside the modal dialog will always deactivate the focus trap.

In this scenario scenario, the modal dialog will not close but the focus will not remain within the modal element as intended. The focus will switch to the modal element and the currently focused element inside the modal (e.g input) will lose focus (only on first time esc is pressed, after that focus trap not active anymore).

Solution:
Pass `false` to `escapeDeactivates` option to _vueuse_'s `useFocusTrap()` (which will pass it to _focus-trap_ library). Since the modal dialog closes anyway when `noCloseOnEsc` is `false` and modal dialog should never lose focus otherwise, making it the default behavior makes sense.

### Reproduction

https://stackblitz.com/edit/github-cw3lum?file=src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by VividLemon**
# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [ ] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

File: packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue [hunk 1]
```diff
@@ -302,29 +302,16 @@ const generateDetailsItem = (item: TableItem): [object, boolean | undefined] =>
...
-        if (isTableItem(el)) {
-          acc.push(generateDetailsItem(el))
-        }
-        return acc
-      },
-      [] as [object, boolean | undefined][]
-    )
-  )
-)
+const detailsMap = ref(new WeakMap())
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue:305]:
```suggestion
const detailsMap = ref(new WeakMap<object, boolean | undefined>())
```
