### PR TITLE
fix(BTable): emitting and listening to hover events

### LINKED ISSUE #1687: BTable rowHovered event is not working
### Describe the bug

The documentation defines the BTable `rowHovered` and `rowUnhovered` events, but even when set, I cannot obtain the hover events.
https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/table.html#comp-reference-btable-events

Event | Args
-- | --
rowHovered | item: TableItem<br>index: number<br>event: MouseEvent
rowUnhovered | item: TableIte<br>mindex: number<br>event: MouseEvent

It was usable with BTableLite. It seems that it is not working properly because BTableLite emits `rowHovered`, but it is not being received by BTable.

### Reproduction

https://stackblitz.com/edit/bootstra-vue-next-template-q5pacf?file=src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by aivy3**
# Describe the PR
fix #1687 
emitting and listening to hover events on BTable

## Small replication

https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/53003820/d6631fb2-0724-4239-b073-9866e51cfc2e

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

File: packages/bootstrap-vue-next/src/components/BTable/BTable.vue [hunk 1]
```diff
@@ -9,6 +9,8 @@
     :field-column-class="getFieldColumnClasses"
     @head-clicked="onFieldHeadClick"
     @row-clicked="onRowClick"
+    @row-hovered="(row, index, e) => emit('row-hovered', row, index, e)"
+    @row-unhovered="(row, index, e) => emit('row-unhovered', row, index, e)"
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BTable/BTable.vue:13]:
```suggestion
    @row-hovered="(row, index, e) => { emit('row-hovered', row, index, e) }"
    @row-unhovered="(row, index, e) => { emit('row-unhovered', row, index, e) }"
```
This will have a lint issue that will need to be fixed.

**Review by VividLemon — CHANGES_REQUESTED** [review]

**Comment by VividLemon** [comment]
tyvm
