### PR TITLE
fix(Table): various functional syntaxes in attrs & classes fixes #2083

### LINKED ISSUE #2083: BTable field tdClass as callback function no longer works
### Describe the bug

In original bootstrap-vue, a BTable field tdClass could be defined as a callback function as follows:
image
https://bootstrap-vue.org/docs/components/table#field-definition-reference

But in bootstrap-vue-next, a callback function no longer works. A simple string value does work.

The linked StackBlitz repro demonstrates both cases.

### Reproduction

https://stackblitz.com/edit/github-jwsdlr-jjprq1?file=src%2Fcomponents%2FComp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by VividLemon**
# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [ ] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

File: packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue [hunk 1]
```diff
@@ -160,9 +174,8 @@
           :class="getFieldColumnClasses(field)"
           :title="field.headerTitle"
           :abbr="field.headerAbbr"
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue:176]:
```suggestion
          :abbr="field.headerAbbr"
          :style="field.thStyle"
```
