### PR TITLE
fixed BTableLite item _showDetails

### LINKED ISSUE #1881: BTableLite _showDetails never change
### Describe the bug

After #1879  ```_showDetails``` in items never change

### Reproduction

https://stackblitz.com/edit/github-m6wxp7?file=src%2Fcomponents%2FComp.vue,src%2FApp.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by makroxyz**
# Describe the PR

fix #1881

### CODE REVIEW

File: packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue [hunk 1]
```diff
@@ -361,6 +361,7 @@ const toggleRowDetails = (tr: T) => {
   if (isTableItem(tr)) {
     const prevValue = detailsMap.value.get(tr)
     detailsMap.value.set(tr, !prevValue)
+    tr._showDetails = !prevValue
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue:364]: This line will subsequently cause this watcher https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1882/files#diff-798f265faf0ec8e8d395983b2a3e9eb972f91083f5f91852178ead74b95e4c93R292 to trigger. Its not infinite, but seems like a potential issue. Not sure the best way to fix this as by definition, 'tr' could be readonly (`readonly(ref([]))` or `computed`)

Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue:364]: Practically speaking, it probably makes no difference :thinking:

**Review by VividLemon — CHANGES_REQUESTED** [review]

File: packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue (hunk 1 above)
Comment (makroxyz) [reply packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue:364]: So, what can we do? 
Without this PR all tables with details I have in project which use _showDetail in items are dead
