### PR TITLE
Fix-backdrop-flicker

### LINKED ISSUE #2365: Regression: BModal's background is now "flashing" when the BModal opens
### Describe the bug

Hi,
I have the same problem again as described [here](https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2260#issuecomment-2407680345).

When I open a BModal with version 0.26.1, I have the background that "flashes" briefly.
It is hard to notice on a white page, but very visible on a page with many components (and colors).

### Reproduction
1. Go to https://stackblitz.com/edit/github-rzxbjv-mnhfku
2. Click on the "Open Modal" button, you'll see that background color briefly switches between two colors

Note that with version 0.25.13, the problem doesn't occur: https://stackblitz.com/edit/github-rzxbjv-gqgmmn

### Reproduction

https://stackblitz.com/edit/github-rzxbjv-mnhfku

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by xvaara**
# Describe the PR

fixes #2365

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

**Review by VividLemon — APPROVED** [review]

File: packages/bootstrap-vue-next/src/composables/useShowHide.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import {computed, type EmitFn, nextTick, onMounted, type Ref, ref, watch} from 'vue'
 import {BvTriggerableEvent} from '../utils'
-import {useEventListener} from '@vueuse/core'
+import {useEventListener, useThrottleFn} from '@vueuse/core'
```
Comment (dwgray) [inline packages/bootstrap-vue-next/src/composables/useShowHide.ts:3]: vueuse is amazing!
