### PR TITLE
fix resolver paths

### LINKED ISSUE #2192: Failed to resolve component v0.24.13
### Describe the bug

It seems that there was a path error in version 0.24.13, and I noticed that you made changes to `BTab` in version 0.24.14 to address this issue. (https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2185)

The same issue is occurring not only with the `BTab` component but also with `BCloseButton` and `BTransition`.

Thank you.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-zbf8aj?file=src%2Fpages%2Findex.vue

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by xvaara**
# Describe the PR

fixes #2192

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

File: packages/bootstrap-vue-next/src/types/BootstrapVueOptions.ts [hunk 1]
```diff
@@ -108,6 +108,7 @@ export const componentsWithExternalPath = {
   BThead: '/components/BTable',
   BTfoot: '/components/BTable',
   BTr: '/components/BTable',
+  BTransition: '/components/BTransition.vue',
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/types/BootstrapVueOptions.ts:111]: https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2192#issuecomment-2351014521

**Review by VividLemon — CHANGES_REQUESTED** [review]

File: packages/bootstrap-vue-next/src/components/index.ts [hunk 2]
```diff
@@ -37,3 +37,4 @@ export * from './BTable'
 export * from './BTabs'
 export * from './BToast'
 export * from './BTooltip'
+export {default as BTransition} from './BTransition.vue'
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/index.ts:40]:
```suggestion
```

File: packages/bootstrap-vue-next/src/types/BootstrapVueOptions.ts (hunk 1 above)
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/types/BootstrapVueOptions.ts:111]:
```suggestion
```

**Review by VividLemon — APPROVED** [review]
