### PR TITLE
change renderorskip to wrapper, add our own teleport logic.

### LINKED ISSUE #1936: BDropdown changes v0.20.0
**What you are trying to do.** A clear and concise description of what you want to happen.

Hi, the new version v0.20.0 makes some changes to BDropdowns - what do they do? I've been looking through the code and I'm not sure what is going on - only that after the update I have some issues rendering my components contents/items, v0.19 had some issues but not this. I need to wrap my BDropdowns with `<ClientOnly>` tags now to get them to render their contents. Any input is appreciated! Many thanks.

**What you have already tried.** A clear and concise description of any alternative solutions or features you have considered.

Wrapping my BDropdowns in  `<ClientOnly>` tags which isn't ideal. Needed for page reloads.

**Any error messages you are getting.** If any, please list the errors you are getting.

image

This is thrown when clicking on the dropdown.

**Environment (please complete the following information):**

- OS: linux Ubuntu v22.04
- Package Version: 0.20.0
- Npm/Yarn/Pnpm/Bun Version: yarn v1.22.19

### LINKED ISSUE #1972: BNavItemDropdown broken on Nuxt?
### Describe the bug

Create a new Nuxt 3 project. Pick the default options.

```
$ npx nuxi@latest init b-nav-item-dropdown-example
$ cd b-nav-item-dropdown-example
```

Install `bootstrap`, `bootstrap-vue-next` and `@bootstrap-vue-next/nuxt`:

```
$ npm install --save-dev bootstrap bootstrap-vue-next @bootstrap-vue-next/nuxt
```

Add `modules: ['@bootstrap-vue-next/nuxt'],` and `css: ['bootstrap/dist/css/bootstrap.min.css'],` to `nuxt.config.ts`.

Replace `app.vue` with:

```html
<template>
  <BNavItemDropdown text="Test">
    <BDropdownItem>Test</BDropdownItem>
  </BNavItemDropdown>
</template>
```

Start the project:

```
$ npm run dev
```

Click on the dropdown. Note the error in the console (“TypeError: el is null”).

Including all composables and directives didn't make a difference.

I've tried some other components (like `BButton`) and they have worked fine.

There's also a hydration mismatch.

The same code worked on StackBlitz.

### Reproduction

N/A

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #2024: BDropdown issues
### Describe the bug

There's 2 issues I've noticed whilst using the `BDropdown` component.

1. When focusing on to the dropdown using Tab, use the up or down arrow keys on your keyboard - Notice 100's of tabs open causing page to crash
2. I am using the Nuxt module, the dropdown won't open on page refresh without the use of `<client-only>` wrapping the dropdown component

### Reproduction

https://stackblitz.com/edit/nuxt-starter-csegoj?file=app.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #2046: `BDropdown` not working on bootstrap-vue-next.github.io
### Describe the bug

Hey,

It seems that the dropdown components (available [here](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/dropdown.html) or [here](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/navbar.html#bnavitemdropdown) for instance) are not working at all. This could be related to #2024 and #1972.

Here's the console content :

image

### Reproduction

Go to [this page](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/dropdown.html) with a Chromium browser. Not tested on Firefox or Safari tho.

EDIT : It seems to happen only when rendered server side. So if it works while testing, try to _F5_ the page before retrying 🙂

### Used Package Manager

n/a

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### LINKED ISSUE #2157: Navbar not work with NUXT 3.12.4
### Describe the bug

"nuxt": "^3.12.4",
"@bootstrap-vue-next/nuxt": "^0.24.11",

create a page in nuxt, and copy code from https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/navbar.html 
 
  <BNavbar toggleable="lg" variant="primary" v-b-color-mode="'dark'">
  <BNavbarBrand href="#">NavBar</BNavbarBrand>
  <BNavbarToggle target="nav-collapse" />
  <BCollapse id="nav-collapse" is-nav>
    <BNavbarNav>
      <BNavItem href="#">Link</BNavItem>
      <BNavItem href="#" disabled>Disabled</BNavItem>
    </BNavbarNav>
    
    <BNavbarNav class="ms-auto mb-2 mb-lg-0">
      <BNavItemDropdown text="Lang" right>
        <BDropdownItem href="#">EN</BDropdownItem>
        <BDropdownItem href="#">ES</BDropdownItem>
        <BDropdownItem href="#">RU</BDropdownItem>
        <BDropdownItem href="#">FA</BDropdownItem>
      </BNavItemDropdown>
      <BNavItemDropdown right>
        
        <template #button-content>
          <em>User</em>
        </template>
        <BDropdownItem href="#">Profile</BDropdownItem>
        <BDropdownItem href="#">Sign Out</BDropdownItem>
      </BNavItemDropdown>
    </BNavbarNav>
    <BNavForm class="d-flex">
      <BFormInput class="me-2" placeholder="Search" />
      <BButton type="submit" variant="outline-success">Search</BButton>
    </BNavForm>
  </BCollapse>
</BNavbar> 

got a error 

runtime-core.esm-bundler.js?v=35ddb965:4614 Uncaught (in promise) TypeError: Cannot set properties of null (setting '__vnode')
    at patchElement (runtime-core.esm-bundler.js?v=35ddb965:4614:18)
    at processElement (runtime-core.esm-bundler.js?v=35ddb965:4497:7)
    at patch (runtime-core.esm-bundler.js?v=35ddb965:4354:11)
    at patchKeyedChildren (runtime-core.esm-bundler.js?v=35ddb965:5271:9)

if i delete `BNavItemDropdown` part , other works ok.

### Reproduction

what

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by xvaara**
# Describe the PR

This fixes the teleport problems are having. It seems upstream isn't interested in fixing this any time soon.
Renamed render or skip to BWrapper. 

closes #1972 
closes #2157 
closes #1936 
closes #2024
closes #2046

maybe even more

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

File: packages/bootstrap-vue-next/src/components/BTeleport.vue [hunk 1]
```diff
@@ -2,32 +2,27 @@
 import {defineComponent, h, type PropType, type SlotsType, Teleport, type TeleportProps} from 'vue'
 
 export default defineComponent({
-  name: 'RenderComponentOrSkip',
+  name: 'BTeleport',
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BTeleport.vue:5]: It would be beneficial to rebase this to my branch https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2147 . The structure of the directories have changed (read README).

Second, let's make these internal components have a name not prepended with `B` to also indicate that they are not exposed components

**Review by VividLemon — CHANGES_REQUESTED** [review]

File: packages/bootstrap-vue-next/src/components/BTeleport.vue (hunk 1 above)
Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BTeleport.vue:5]: When you've done that, feel free to merge request this PR into my PR. That would make things easier ig

File: packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue [hunk 2]
```diff
@@ -354,3 +351,4 @@ provide(dropdownInjectionKey, {
   isNav: toRef(() => props.isNav),
 })
 </script>
+../BWrapper.vue
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue:354]:
```suggestion
```

File: packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue [hunk 3]
```diff
@@ -122,3 +122,4 @@ defineExpose({
   },
 })
 </script>
+../BWrapper.vue
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue:125]:
```suggestion
```

File: packages/bootstrap-vue-next/src/components/BTeleport.vue
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BTeleport.vue:1]: Rename this file. It is not an exposed component so it doesn't make sense to have it prefixed with "B".

File: packages/bootstrap-vue-next/src/components/BWrapper.vue
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BWrapper.vue:1]: Rename this file. It is not an exposed component so it doesn't make sense to have it prefixed with "B".

**Review by VividLemon — CHANGES_REQUESTED** [review]

File: packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue (hunk 2 above)
Comment (xvaara) [reply packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue:354]: Something adds these in :D

File: packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue [hunk 4]
```diff
@@ -346,3 +350,4 @@ defineExpose({
   show,
 })
 </script>
+../ConditionalTeleport.vue
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue:353]:
```suggestion
```

File: packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue [hunk 5]
```diff
@@ -354,3 +358,4 @@ provide(dropdownInjectionKey, {
   isNav: toRef(() => props.isNav),
 })
 </script>
+../ConditionalTeleport.vue
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue:361]:
```suggestion
```

File: packages/bootstrap-vue-next/src/components/BModal/BModal.vue [hunk 6]
```diff
@@ -519,3 +522,4 @@ defineExpose({
   z-index: 1051;
 }
 </style>
+../ConditionalTeleport.vue
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BModal/BModal.vue:525]:
```suggestion
```

File: packages/bootstrap-vue-next/src/components/BModal/BModalOrchestrator.vue [hunk 7]
```diff
@@ -55,3 +56,4 @@ defineExpose({
   ...tools,
 })
 </script>
+../ConditionalTeleport.vue
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BModal/BModalOrchestrator.vue:59]:
```suggestion
```

File: packages/bootstrap-vue-next/src/components/BPopover/BPopover.vue [hunk 8]
```diff
@@ -486,3 +490,4 @@ onMounted(bind)
 
 onBeforeUnmount(unbind)
 </script>
+../ConditionalTeleport.vue
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BPopover/BPopover.vue:493]:
```suggestion
```

File: packages/bootstrap-vue-next/src/components/BToast/BToastOrchestrator.vue [hunk 9]
```diff
@@ -82,3 +83,4 @@ I think it's because it's "moving", but I don't know where it's moving to
   position: fixed;
 }
 </style>
+../ConditionalTeleport.vue
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BToast/BToastOrchestrator.vue:86]:
```suggestion
```

**Review by VividLemon — APPROVED** [review]
