### PR TITLE
fix(BTable): make foot props and slot fall back to head if not defined

### LINKED ISSUE #2538: Make Table footer props and slots fall back to header definitions
### Missing feature is from

bootstrap-vue

### Docs

https://bootstrap-vue.org/docs/components/table#header-and-footer-custom-rendering-via-scoped-slots

### Describe the missing feature

In BSV, when a footer-specific prop or slot is not defined (and foot-clone===true), the footer prop or slot falls back to the one defined for the header.

The instances of this that I've found, which may not be a complete list

- [ ] foot-row-variant should fall back to head-row-variant
- [ ] #foot() and #foot(name) should fall back to #head() and #head(name)

### PR DESCRIPTION
**Pull request by dwgray**
# Describe the PR

fixes #2538

- If `footVariant`, `footRowVariant`, `footClass` and `footTrClass` aren't specified, fall back to the equivalent `head` props.
- If the `foot()` or `foot(*)` slot isn't defined, fall back to the equivalent `head` slot 
    - Add some documentation to how this fallback works, as I misread the BSV docs and implemented it incorrectly the first time
- Add unit tests for this and related behavior

## Small replication

See unit tests in this PR

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

File: packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue [hunk 1]
```diff
@@ -170,15 +173,12 @@
           <div class="d-inline-flex flex-nowrap align-items-center gap-1">
             <div>
               <!-- eslint-disable prettier/prettier -->
+              <!-- @vue-expect-error - typescript is generating 2322 errors for all properties after name, which is wrong -->
```
Comment (dwgray) [inline packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue:176]: I'm reasonably certain that the errors I'm suppressing here are a TS bug. They only show up on the fields when I've added some complexity to the `:name`, but have nothing to do with `name`. Also, only `vue-expect-error` is depressing the error, `vue-ignore` isn't. I did some digging into this, but I don't think getting further into it is the best use of my time right now, unless you see something obviously weird that I'm doing here.

```
src/components/BTable/BTableLite.vue:179:18 - error TS2322: Type 'string | undefined' is not assignable to type 'never'.
  Type 'undefined' is not assignable to type 'never'.

179                 :label="field.label"
                     ~~~~~

src/components/BTable/BTableLite.vue:180:18 - error TS2322: Type 'string | number | symbol | (string & Record<never, never>)' is not assignable to type 'never'.
  Type 'string' is not assignable to type 'never'.

180                 :column="field.key"
                     ~~~~~~

src/components/BTable/BTableLite.vue:181:18 - error TS2322: Type 'TableField<Items> & { _noHeader?: true | undefined; }' is not assignable to type 'never'.

181                 :field="field"
                     ~~~~~

src/components/BTable/BTableLite.vue:182:18 - error TS2322: Type 'boolean' is not assignable to type 'never'.

182                 :is-foot="true"
                     ~~~~~~

```

Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue:176]: Merge the current version of main (`pnpm i`) and see if it fixes this issue

Comment (dwgray) [reply packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue:176]: Merged. I get the same errors if I remove `vue-expect-error`

**Review by VividLemon — APPROVED** [review]

File: packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue (hunk 1 above)
Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue:176]: Probably fine
