### PR TITLE
 fix(nuxt): make injection keys static strings fixes #2209 

### LINKED ISSUE #2209: [Vue warn]: injection "Symbol(bvn::toastPlugin)" not found.
### Describe the bug

I'm not sure if this is an issue with Nuxt or Vue, but when updating my project with the latest versions of nuxt, vue, and bootstrap-vue-next, toasts that are created with the `useToast` composable are not appearing anymore with the following warning in the console: 

```
[Vue warn]: injection "Symbol(bvn::toastPlugin)" not found. 
  at <App key=4 > 
  at <NuxtRoot>
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-21x7kb?file=app.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by VividLemon**
# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [ ] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

File: packages/bootstrap-vue-next/src/utils/bvnPrefix.ts [hunk 1]
```diff
@@ -0,0 +1,4 @@
+export const bvnPrefix = (value: string, suffix: string = '') => {
+  const suffixWithTrail = `${suffix}___`
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/utils/bvnPrefix.ts:2]:
```suggestion
  const suffixWithTrail = `${suffix}__`
```
