### PR TITLE
Navbar fixes

### LINKED ISSUE #1283: [BNavItem] Allow disabling navbar auto-collapse
When you click on a `b-nav-item` in a `b-collapse` inside a `b-navbar`, the `b-collapse` is auto collapsed. This behavior has [recently](https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1090) been altered; now it auto-collapses `b-collapse` solely in `b-navbar`.

I am using a `b-navbar` in my sidebar, styled it to be vertical, and added some `b-nav-item` and `b-collapse` components, a few levels deep. If I click on an item on e.g. the third level,  the parent `b-collapse` auto-collapses. I would like to be able to opt-out of this behavior.

I tried adding the `is-nav` prop to the `b-collapse` component, but (correct me if I'm wrong) that only "force"-shows the content, and disables the ability to `show` or `hide` the `b-collapse` via the `v-b-toggle` directive.

### LINKED ISSUE #1393: BNavItemDropdown is missing show & hide events
**Is this feature a Bootstrap-vue feature?** 
see: https://bootstrap-vue.org/docs/components/nav#comp-ref-b-nav-item-dropdown-events
@hide is not handled/firing:
`
<b-nav-item-dropdown left no-caret @hide="showStatus = false">
   <b-dropdown-item v-for="status in statuses" :key="status.id" @click="selectedStatus = status">{{ status.name }}</b-dropdown-item>
</b-nav-item-dropdown>
`

**Additional context.** 
show en hide are emitted from BDropdown child component, but they are not emitted from BNavItemDropdown

### PR DESCRIPTION
**Pull request by xvaara**
fix(BNavItemDropdown): all props and emits from dropdown
closes #1393 
feat(BNavbar): add auto-close to disable collapse closing
closes #1283

### CODE REVIEW

File: packages/bootstrap-vue-next/src/components/BLink/BLink.vue [hunk 1]
```diff
@@ -164,7 +159,10 @@ const clicked = (e: MouseEvent): void => {
     return
   }
 
-  if (collapseData?.isNav?.value === true) {
+  if (
+    (collapseData?.isNav?.value === true && navbarData === null) ||
+    (navbarData !== null && navbarData?.autoClose?.value === true)
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BLink/BLink.vue:164]:
```suggestion
    (navbarData !== null && navbarData.autoClose?.value === true)
```

File: packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue [hunk 2]
```diff
@@ -15,65 +28,101 @@
...
-import type {Booleanish, ButtonVariant, ClassValue, Size} from '../../types'
-import {omit} from '../../utils'
+import type {Boundary, Middleware, RootBoundary, Strategy} from '@floating-ui/vue'
+import {ref} from 'vue'
+import type {Booleanish, ButtonType, ButtonVariant, ClassValue, Size} from '../../types'
+import {BvTriggerableEvent} from '../../utils'
 import BDropdown from '../BDropdown/BDropdown.vue'
+import type {RouteLocationRaw} from 'vue-router'
 
 // TODO share props with BDropdown
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue:38]: You may be better off implementing this TODO note

**Review by VividLemon — CHANGES_REQUESTED** [review]

File: packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue (hunk 2 above)
Comment (xvaara) [reply packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue:38]: It seems like vue doesn't yet implement complex props with typescript. They have one difference (isNav) so the need to have their own. Or am I mistaken here? I did think of that and tried to look it up, and came to that conclusion.

Other component that could use this is the tooltip.

Comment (xvaara) [reply packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue]: Well it works with the same props now.

File: packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue [hunk 3]
```diff
@@ -74,95 +74,91 @@ import {onClickOutside, onKeyStroke, useToNumber, useVModel} from '@vueuse/core'
...
-    noCaret: false,
-    toggleText: 'Toggle dropdown',
-    variant: 'secondary',
-    modelValue: false,
-    strategy: 'absolute',
-    splitTo: undefined,
-    boundary: 'clippingAncestors',
-  }
-)
+export interface Props {
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue:84]: Move this to /types/ComponentProps

**Comment by xvaara** [comment]
I'll do a real props merge in a different pull request and take a look at the popover/tooltip props at the sametime.

File: packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue (hunk 2 above)
Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue]: > It seems like vue doesn't yet implement complex props with typescript. They have one difference (isNav) so the need to have their own. Or am I mistaken here? I did think of that and tried to look it up, and came to that conclusion.

I don't understand what you mean here. You're capable of doing these things in complex ways. BTable is a good example of this with extending prop definitions around and omitting certain values -- or blink, which often omits 'event' (and one other prop I forgot the name of). 

Technically you could do `defineProps<Omit<Props, 'isNav'>>` but in this case, the way I see it, it's on them to make such a mistake... Or we could just prevent them from making silly mistakes idrc. Maybe there's a reason to turn off isNav, but probably not.

> It seems like vue doesn't yet implement complex props with typescript 

You'd have to define what this is and what you're trying to do. Because it's not quite clear.

**Review by VividLemon — CHANGES_REQUESTED** [review]

File: packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue (hunk 2 above)
Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue]: Keep in mind, that part of the issue might exist with actually doing

```ts
export interface Props {
```

in the actual vue file itself. You _can_ do as I described with omit and whatnot, but you can't do it if it's in another Vue file.

File: packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue (hunk 3 above)
Comment (xvaara) [reply packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue]: done

File: packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue [hunk 4]
```diff
@@ -67,97 +67,53 @@ import {
...
   type RootBoundary,
   shift,
-  type Strategy,
   useFloating,
 } from '@floating-ui/vue'
 import {onClickOutside, onKeyStroke, useToNumber, useVModel} from '@vueuse/core'
 import {computed, provide, readonly, ref, toRef, watch} from 'vue'
 import {useBooleanish, useId} from '../../composables'
-import type {Booleanish, ButtonType, ButtonVariant, ClassValue, Size} from '../../types'
+import type {BDropdownProps} from 'src/types'
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue:75]: SRC/types is invalid
