### PR TITLE
fix(BFormCheckbox): Handle contextual state === false correctly (Fixes #2017)

### LINKED ISSUE #2017: :state="false" on BFormCheckbox
### Describe the bug

Shouldn't the first checkbox on https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-checkbox.html#contextual-state-and-validation-example be red since the `state` prop is set to `false`?

I have a required checkbox that I want to highlight in red under certain circumstances.

This code didn't produce a checkbox at all on StackBlitz for some reason:

```html
<BFormCheckbox :state="false">Should be red</BFormCheckbox>
```

### Reproduction

N/A

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by dwgray**
# Describe the PR

Checkbox `state === false` was resolving to undefined (which is effectively the null state) if there was no parent. Instead of using the parent value for all `falsey` values, I'm checking that the direct prop is `true` or `false` and only falling back to the parent if it's not.

## Small replication

See #2017 

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

File: packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue [hunk 1]
```diff
@@ -115,7 +115,8 @@ const classesObject = computed(() => ({
   inline: props.inline || (parentData?.inline.value ?? false),
   reverse: props.reverse || (parentData?.reverse.value ?? false),
   switch: props.switch || (parentData?.switch.value ?? false),
-  state: props.state || parentData?.state.value,
+  state:
+    props.state === true || props.state === false ? props.state : parentData?.state.value ?? null,
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue:119]: Why not `props.state ?? parentData?.state.value ?? null`

**Comment by dwgray** [comment]
When `props === false` and `parent === undefined`, `props.state ?? parentData?.state.value ?? null` evaluates to `null`, we want it to evaluate to `false` (that's what this bug is about)

So, if we did `props.state ?? parentData?.state.value ?? false`, that would catch the case that the bug is about, but if `props.state === null`, then we have the same problem (we get `false` when we want `null`)

Semantically, I think what we want to say is that if `props.state` is a boolean, use that, otherwise, use `parentData.state` and fall back to `null` if `parentData` doesn't exist. I don't see a cleaner way to state that, but I'm open to suggestions.

**Review by VividLemon — APPROVED** [review]
