### PR TITLE
fix(BTable)!: fix a long standing regression in which the comparer fu…

### LINKED ISSUE #2565: There is no way to define and use 'comparer' for custom rendered fields in  BTable
### Describe the bug

The 'comparer' in custom rendered fields does not receive any data in 'a' and 'b' fields

See the example where the custom column 'full_name' is based on first_name + last_name fields, it is sortable and has comparer defined.
The sorting by this column invoks the comparer but without any data.

https://stackblitz.com/edit/vitejs-vite-128junot?file=src%2Fcomponents%2FHelloWorld.vue

IMHO, the comparer should not receive merely the 'a' and 'b' values extracted from the data model supplied to the table. Instead, it should be provided with a complete 'item' element representing the entire row of data. The comparer function, in turn, should determine which field to extract from the 'item' and how to compare it, based on its internal logic.

This approach aligns with the previous implementation in Vue-Bootstrap for Vue 2. It remains unclear why a redesign was necessary for a well-functioning system, only to introduce avoidable regressions.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-128junot?file=src%2Fcomponents%2FHelloWorld.vue

### Used Package Manager

pnpm

### PR DESCRIPTION
**Pull request by VividLemon**
…nction in btable did not give the item value, instead passing a string fixes #2565

# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [ ] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

File: packages/bootstrap-vue-next/src/components/BTable/BTable.vue [hunk 1]
```diff
@@ -706,11 +706,10 @@ const computedItems = computed<Items[]>(() => {
             : (val?.toString() ?? '')
         }
 
-        const aValue = realVal(a)
-        const bValue = realVal(b)
         const comparison = sortOption.comparer
-          ? sortOption.comparer(aValue, bValue)
-          : aValue.localeCompare(bValue, undefined, {numeric: true})
```
Comment (tbl0605) [inline packages/bootstrap-vue-next/src/components/BTable/BTable.vue:713]: Would it be possible to add the field key being sorted as third argument of `sortOption.comparer(a, b)` like it was done for the original bootstrap-vue [custom sort-compare routine](https://bootstrap-vue.org/docs/components/table#custom-sort-compare-routine)?

Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BTable/BTable.vue:713]: Done
