### PR TITLE
fix(BDropdownItem): attrs inheritance fixes #1591

### LINKED ISSUE #1591: BDropdownItem does not handle id param
### Describe the bug

A added id parameter will be ignored, which makes it very difficult to simulate a click on a dropdown menu item in automated tests like codeception.

Additional there is a css class "text-undefined" attached to the generated button tag, which makes imo no sense.

### Reproduction

Not needed

### System Info

```Shell
Any
```

### Used Package Manager

yarn

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by VividLemon**
# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [ ] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

File: packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItem.vue [hunk 1]
```diff
@@ -35,11 +35,13 @@ const props = withDefaults(
   defineProps<
     {
       linkClass?: ClassValue
+      wrapperAttrs?: AttrsValue
     } & Omit<BLinkProps, 'event' | 'routerTag'>
   >(),
   {
     // Link props
     linkClass: undefined,
+    wrapperAttrs: undefined,
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItem.vue:44]:
```suggestion
    wrapperAttrs: undefined,
    // Link props
    linkClass: undefined,
```
