### PR TITLE
 fix(BPagination): centering of arrows when using span fixes #2135 

### LINKED ISSUE #2135: BPagination pills align='fill' right arrow display error
### Describe the bug

image

### Reproduction

none

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by VividLemon**
# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix :bug: - `fix(...)`
- [ ] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [ ] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

File: packages/bootstrap-vue-next/src/types/CommonTypes.ts [hunk 1]
```diff
@@ -1,8 +1,30 @@
...
+  opacityHover?: 10 | 25 | 50 | 75 | 100 | '10' | '25' | '50' | '75' | '100'
+}
+
+export interface LinkIconProps {
+  icon?: boolean
+}
+
+export interface LinkVariantProps {
+  variant?: ColorVariant | null
+}
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/types/CommonTypes.ts:30]:
```suggestion
```

File: packages/bootstrap-vue-next/src/types/CommonTypes.ts [hunk 2]
```diff
@@ -1,4 +1,5 @@
 import type {TeleportProps} from 'vue'
+import type {ColorVariant} from './ColorTypes'
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/types/CommonTypes.ts:2]:
```suggestion
```
