### PR TITLE
Dropdown input group fixes

### LINKED ISSUE #1907: Dropdown radius broken
### Describe the bug

https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/input-group.html#dropdown-addons
When using Dropdown in InputGroup, the radius of the button does not seem to fit correctly.
The menu displayed also had a radius of 0 for the right half.

The same was true in the official documentation.
```vue
<BForm>
  <BInputGroup>
    <BDropdown text="Test">
      <BDropdownItem>abcdef</BDropdownItem>
      <BDropdownItem>ghijkl</BDropdownItem>
    </BDropdown>
    <BInputGroupText>Txt</BInputGroupText>
    <BFormInput placeholder="hello" />
  </BInputGroup>
</BForm>
```

bs-dropdown

### Reproduction

https://stackblitz.com/edit/github-4brggy

### Used Package Manager

bun

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by xvaara**
fixes #1907 
BEGIN_COMMIT_OVERRIDE
fix(BDropdown): fix wrapper class, skip wrapper in input-group
feat(BDropdown): add skipWrapper and wrapperClass props
END_COMMIT_OVERRIDE

# Describe the PR

A clear and concise description of what the pull request does.

## Small replication

A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also works.

## PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix :bug: - `fix(...)`
- [x] Feature - `feat(...)`
- [ ] ARIA accessibility - `fix(...)`
- [ ] Documentation update - `docs(...)`
- [ ] Other (please describe)

**The PR fulfills these requirements:**

- [x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**

### CODE REVIEW

File: packages/bootstrap-vue-next/src/utils/keys.ts [hunk 1]
```diff
@@ -208,3 +208,5 @@ export const modalManagerPluginKey: InjectionKey<{
 export const idPluginKey: InjectionKey<() => string> = Symbol('bvn::idPluginKey')
 
 export const defaultsKey: InjectionKey<Ref<Partial<BvnComponentProps>>> = Symbol('bvn::defaults')
+
+export const inputGroupKey: InjectionKey<Ref<boolean>> = Symbol('bvn::inputGroup')
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/utils/keys.ts:212]: This can just be a boolean to avoid the need to make a Ref. It doesn't even really need to return anything (but boolean is easier on the TS)

**Review by VividLemon — CHANGES_REQUESTED** [review]

File: packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue [hunk 2]
```diff
@@ -262,10 +276,13 @@ const {update, floatingStyles} = useFloating(referencePlacement, floating, {
...
 
 const computedClasses = computed(() => ({
+  'btn-group': !props.wrapperClass && props.split,
+  'dropdown': !props.wrapperClass && !props.split,
   'dropup': props.dropup,
   'dropend': props.dropend,
   'dropstart': props.dropstart,
   'position-static': props.boundary !== 'clippingAncestors' && !props.isNav,
+  [props.wrapperClass]: props.wrapperClass,
 }))
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue:286]:
```suggestion
const computedClasses = computed(() => [ props.wrapperClass, {
  'btn-group': !props.wrapperClass && props.split,
  'dropdown': !props.wrapperClass && !props.split,
  'dropup': props.dropup,
  'dropend': props.dropend,
  'dropstart': props.dropstart,
  'position-static': props.boundary !== 'clippingAncestors' && !props.isNav,
}])
```

**Review by VividLemon — CHANGES_REQUESTED** [review]

File: packages/bootstrap-vue-next/src/components/BDropdown/dropdown.spec.ts [hunk 3]
```diff
@@ -11,11 +11,27 @@ describe('dropdown', () => {
     expect(wrapper.element.tagName).toBe('DIV')
   })
 
-  it('has static class btn-group', () => {
+  it('has static class dropdown', () => {
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BDropdown/dropdown.spec.ts:14]: This is just a comment, but putting the tests together can be a bit quicker. I used to split them all up. But I find myself doing more tests if I'm writing less boilerplate and making a single "has classes on root el"-like test
